name: Build and Deploy - Luzyce.WebApp

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        run: |
          docker login --username ddnowicki --password ${{ secrets.GH_PAT }} ghcr.io
      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/luzyce/luzyce-webapp:latest -f apps/src/Luzyce.WebApp/Dockerfile .
      - name: Push the Docker image
        run: |
          docker push ghcr.io/luzyce/luzyce-webapp:latest

  deploy-develop:
    runs-on: [self-hosted, prod-luzyce-webapp]
    environment: Develop
    needs: build-and-push-image
    steps:
      - name: Log in to GitHub Container Registry
        run: |
          docker login --username ddnowicki --password ${{ secrets.GH_PAT }} ghcr.io

      - name: Stop & clean old containers
        run: |
          if [ $(docker ps -q -f name=luzycewebapp) ]; then
            docker stop luzycewebapp
          fi
          if [ $(docker ps -aq -f name=luzycewebapp) ]; then
            docker rm luzycewebapp
          fi
          if [ $(docker images -q ghcr.io/luzyce/luzyce-webapp:latest) ]; then
            docker rmi -f ghcr.io/luzyce/luzyce-webapp:latest
          fi

      - name: Pull Docker image from GitHub Container Registry
        run: |
          docker pull ghcr.io/luzyce/luzyce-webapp:latest

      - name: Run Docker container
        run: |
          docker run \
            -d \
            -p 35133:35133 \
            -e ASPNETCORE_HTTP_PORTS=35133 \
            -e ASPNETCORE_ENVIRONMENT=Development \
            --name luzycewebapp \
            ghcr.io/luzyce/luzyce-webapp:latest

      - name: Check container logs
        run: |
          sleep 10
          docker logs $(docker ps -q --last 1)